run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocyclo
    - unconvert
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # disregard errors not requiring explicit handling
      - G204 # allow subprocess launching with validated config inputs

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

