on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build
        run: bazel build //...

      - name: Lint and Format Check
        run: |
          bazel run //:fmt
          bazel run //:lint

      - name: Test with Coverage
        run: bazel coverage //...

      - name: Generate Coverage Report
        run: |
          TESTLOGS_DIR=$(bazel info bazel-testlogs)
          find "$TESTLOGS_DIR" -name "coverage.dat" -exec cat {} \; > coverage.out

      - name: Upload test coverage report
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
