on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build
        run: bazel build //...

      - name: Lint and Format Check
        run: |
          bazel run //:fmt
          bazel run //:lint

      - name: Test with Coverage
        run: bazel coverage //...

      - name: Install lcov for HTML report generation
        run: sudo apt-get install -y lcov

      - name: Generate HTML Coverage Report
        run: |
          TESTLOGS_DIR=$(bazel info bazel-testlogs)
          mkdir -p coverage-html
          find "$TESTLOGS_DIR" -name "coverage.dat" -exec cat {} \; > coverage.out
          genhtml coverage.out --output-directory coverage-html --title "Code Coverage Report"

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/main'

      - name: Upload coverage report to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: './coverage-html'

  deploy-pages:
    needs: checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
