on:
  release:
    types: [created]

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            target: task-runner-launcher-linux-amd64
          - goos: linux
            goarch: arm64
            target: task-runner-launcher-linux-arm64
            
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build cross-platform binary
        run: bazel build //cmd/launcher:${{ matrix.target }}

      - name: Prepare binary for upload
        run: |
          mkdir -p release-assets
          # Get the actual Bazel output path
          OUTPUT_PATH=$(bazel info output_path)
          cp $OUTPUT_PATH/k8-fastbuild/bin/cmd/launcher/${{ matrix.target }}_/${{ matrix.target }} release-assets/task-runner-launcher
          chmod +x release-assets/task-runner-launcher
          
          # Generate SHA256 sum
          cd release-assets
          sha256sum task-runner-launcher > task-runner-launcher.sha256

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            release-assets/task-runner-launcher#task-runner-launcher-${{ matrix.goos }}-${{ matrix.goarch }} \
            release-assets/task-runner-launcher.sha256#task-runner-launcher-${{ matrix.goos }}-${{ matrix.goarch }}.sha256
